version: "3.8"

volumes:
  es-master1-data:
  es-master2-data:
  es-master3-data:
  es-data1-data:
  es-data2-data:
  es-data3-data:
  es-certs:  # Shared volume for TLS certs

networks:
  esnet:
    driver: bridge

services:
  ###################################################################
  # Elasticsearch Master Nodes
  ###################################################################
  es-master1:
    image: my-elasticsearch:latest
    container_name: es-master1
    environment:
      - node.name=es-master1
      - node.roles=master
      - discovery.seed_hosts=es-master1,es-master2,es-master3,es-data1,es-data2,es-data3
      - cluster.initial_master_nodes=es-master1,es-master2,es-master3
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - network.host=0.0.0.0
    volumes:
      - es-master1-data:/usr/share/elasticsearch/data
      - es-certs:/usr/share/elasticsearch/config/certs
    ports:
      - "9200:9200"
    networks:
      - esnet

  es-master2:
    image: my-elasticsearch:latest
    container_name: es-master2
    environment:
      - node.name=es-master2
      - node.roles=master
      - discovery.seed_hosts=es-master1,es-master2,es-master3,es-data1,es-data2,es-data3
      - cluster.initial_master_nodes=es-master1,es-master2,es-master3
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - network.host=0.0.0.0
    volumes:
      - es-master2-data:/usr/share/elasticsearch/data
      - es-certs:/usr/share/elasticsearch/config/certs
    ports:
      - "9201:9200"
    networks:
      - esnet

  es-master3:
    image: my-elasticsearch:latest
    container_name: es-master3
    environment:
      - node.name=es-master3
      - node.roles=master
      - discovery.seed_hosts=es-master1,es-master2,es-master3,es-data1,es-data2,es-data3
      - cluster.initial_master_nodes=es-master1,es-master2,es-master3
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - network.host=0.0.0.0
    volumes:
      - es-master3-data:/usr/share/elasticsearch/data
      - es-certs:/usr/share/elasticsearch/config/certs
    ports:
      - "9202:9200"
    networks:
      - esnet

  ###################################################################
  # Elasticsearch Data Nodes
  ###################################################################
  es-data1:
    image: my-elasticsearch:latest
    container_name: es-data1
    environment:
      - node.name=es-data1
      - node.roles=data,ingest,transform,ml,remote_cluster_client
      - discovery.seed_hosts=es-master1,es-master2,es-master3,es-data1,es-data2,es-data3
      - cluster.initial_master_nodes=es-master1,es-master2,es-master3
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - network.host=0.0.0.0
    volumes:
      - es-data1-data:/usr/share/elasticsearch/data
      - es-certs:/usr/share/elasticsearch/config/certs
    ports:
      - "9203:9200"
    networks:
      - esnet

  es-data2:
    image: my-elasticsearch:latest
    container_name: es-data2
    environment:
      - node.name=es-data2
      - node.roles=data,ingest,transform,ml,remote_cluster_client
      - discovery.seed_hosts=es-master1,es-master2,es-master3,es-data1,es-data2,es-data3
      - cluster.initial_master_nodes=es-master1,es-master2,es-master3
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - network.host=0.0.0.0
    volumes:
      - es-data2-data:/usr/share/elasticsearch/data
      - es-certs:/usr/share/elasticsearch/config/certs
    ports:
      - "9204:9200"
    networks:
      - esnet

  es-data3:
    image: my-elasticsearch:latest
    container_name: es-data3
    environment:
      - node.name=es-data3
      - node.roles=data,ingest,transform,ml,remote_cluster_client
      - discovery.seed_hosts=es-master1,es-master2,es-master3,es-data1,es-data2,es-data3
      - cluster.initial_master_nodes=es-master1,es-master2,es-master3
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - network.host=0.0.0.0
    volumes:
      - es-data3-data:/usr/share/elasticsearch/data
      - es-certs:/usr/share/elasticsearch/config/certs
    ports:
      - "9205:9200"
    networks:
      - esnet

  ###################################################################
  # Kibana Nodes
  ###################################################################
  kibana1:
    image: docker.elastic.co/kibana/kibana:8.6.2
    container_name: kibana1
    environment:
      - SERVER_NAME=kibana1
      - SERVER_HOST=0.0.0.0
      - ELASTICSEARCH_HOSTS=["https://es-master1:9200","https://es-master2:9200","https://es-master3:9200"]
      - ELASTICSEARCH_SSL_VERIFICATIONMODE=certificate
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=/usr/share/kibana/config/certs/ca/ca.crt
      - SERVER_SSL_ENABLED=true
      - SERVER_SSL_CERTIFICATE=/usr/share/kibana/config/certs/node/es-node/es-node.crt
      - SERVER_SSL_KEY=/usr/share/kibana/config/certs/node/es-node/es-node.key
    volumes:
      - es-certs:/usr/share/kibana/config/certs:ro
    ports:
      - "5601:5601"
    networks:
      - esnet
    depends_on:
      - es-master1

  kibana2:
    image: docker.elastic.co/kibana/kibana:8.6.2
    container_name: kibana2
    environment:
      - SERVER_NAME=kibana2
      - SERVER_HOST=0.0.0.0
      - ELASTICSEARCH_HOSTS=["https://es-master1:9200","https://es-master2:9200","https://es-master3:9200"]
      - ELASTICSEARCH_SSL_VERIFICATIONMODE=certificate
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=/usr/share/kibana/config/certs/ca/ca.crt
      - SERVER_SSL_ENABLED=true
      - SERVER_SSL_CERTIFICATE=/usr/share/kibana/config/certs/node/es-node/es-node.crt
      - SERVER_SSL_KEY=/usr/share/kibana/config/certs/node/es-node/es-node.key
    volumes:
      - es-certs:/usr/share/kibana/config/certs:ro
    ports:
      - "5602:5601"
    networks:
      - esnet
    depends_on:
      - es-master1