version: "3.8"

services:
  ###################################################################
  # 3 Master-Eligible Nodes
  ###################################################################
  es-master1:
    image: my-elasticsearch:latest
    environment:
      - node.name=es-master1
      - node.roles=master
      - discovery.seed_hosts=es-master1,es-master2,es-master3,es-data1,es-data2,es-data3
      - cluster.initial_master_nodes=es-master1,es-master2,es-master3
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - network.host=0.0.0.0           # <-- KEY FIX
    # Persist data on local volume:
    volumes:
      - es-master1-data:/usr/share/elasticsearch/data
    # Publish on local port 9200:
    ports:
      - "9200:9200"
    # All on the same user-defined network:
    networks:
      - esnet

  es-master2:
    image: my-elasticsearch:latest
    environment:
      - node.name=es-master2
      - node.roles=master
      - discovery.seed_hosts=es-master1,es-master2,es-master3,es-data1,es-data2,es-data3
      - cluster.initial_master_nodes=es-master1,es-master2,es-master3
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - network.host=0.0.0.0
    volumes:
      - es-master2-data:/usr/share/elasticsearch/data
    # Publish on local port 9201:
    ports:
      - "9201:9200"
    networks:
      - esnet

  es-master3:
    image: my-elasticsearch:latest
    environment:
      - node.name=es-master3
      - node.roles=master
      - discovery.seed_hosts=es-master1,es-master2,es-master3,es-data1,es-data2,es-data3
      - cluster.initial_master_nodes=es-master1,es-master2,es-master3
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - network.host=0.0.0.0
    volumes:
      - es-master3-data:/usr/share/elasticsearch/data
    # Publish on local port 9202:
    ports:
      - "9202:9200"
    networks:
      - esnet

  ###################################################################
  # 3 Data + Ingest + Transform + ML Nodes
  ###################################################################
  es-data1:
    image: my-elasticsearch:latest
    environment:
      - node.name=es-data1
      - node.roles=data,ingest,transform,ml,remote_cluster_client
      - discovery.seed_hosts=es-master1,es-master2,es-master3,es-data1,es-data2,es-data3
      - cluster.initial_master_nodes=es-master1,es-master2,es-master3
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - network.host=0.0.0.0
    volumes:
      - es-data1-data:/usr/share/elasticsearch/data
    # Publish on local port 9203:
    ports:
      - "9203:9200"
    networks:
      - esnet

  es-data2:
    image: my-elasticsearch:latest
    environment:
      - node.name=es-data2
      - node.roles=data,ingest,transform,ml,remote_cluster_client
      - discovery.seed_hosts=es-master1,es-master2,es-master3,es-data1,es-data2,es-data3
      - cluster.initial_master_nodes=es-master1,es-master2,es-master3
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - network.host=0.0.0.0
    volumes:
      - es-data2-data:/usr/share/elasticsearch/data
    # Publish on local port 9204:
    ports:
      - "9204:9200"
    networks:
      - esnet

  es-data3:
    image: my-elasticsearch:latest
    environment:
      - node.name=es-data3
      - node.roles=data,ingest,transform,ml,remote_cluster_client
      - discovery.seed_hosts=es-master1,es-master2,es-master3,es-data1,es-data2,es-data3
      - cluster.initial_master_nodes=es-master1,es-master2,es-master3
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - network.host=0.0.0.0
    volumes:
      - es-data3-data:/usr/share/elasticsearch/data
    # Publish on local port 9205:
    ports:
      - "9205:9200"
    networks:
      - esnet

# Named volumes for data
volumes:
  es-master1-data:
  es-master2-data:
  es-master3-data:
  es-data1-data:
  es-data2-data:
  es-data3-data:

# Single user-defined network so each container can discover each other by service name
networks:
  esnet:
    driver: bridge
