version: '3.9'

services:
  # Elasticsearch Master Nodes
  es-master1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: es-master1
    environment:
      - node.roles=master
      - cluster.name=elastic-cluster
      - node.name=es-master1
      - bootstrap.memory_lock=true
      - discovery.seed_hosts=es-master1,es-master2,es-master3
      - cluster.initial_master_nodes=es-master1,es-master2,es-master3
      - xpack.security.enabled=true
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=/usr/share/elasticsearch/config/certs/es-master1/es-master1.key
      - xpack.security.transport.ssl.certificate=/usr/share/elasticsearch/config/certs/es-master1/es-master1.crt
      - xpack.security.transport.ssl.certificate_authorities=/usr/share/elasticsearch/config/certs/ca/ca.crt
    volumes:
      - ./certs:/usr/share/elasticsearch/config/certs
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1

  es-master2:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: es-master2
    environment:
      - node.roles=master
      - cluster.name=elastic-cluster
      - node.name=es-master2
      - bootstrap.memory_lock=true
      - discovery.seed_hosts=es-master1,es-master2,es-master3
      - cluster.initial_master_nodes=es-master1,es-master2,es-master3
      - xpack.security.enabled=true
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=/usr/share/elasticsearch/config/certs/es-master2/es-master2.key
      - xpack.security.transport.ssl.certificate=/usr/share/elasticsearch/config/certs/es-master2/es-master2.crt
      - xpack.security.transport.ssl.certificate_authorities=/usr/share/elasticsearch/config/certs/ca/ca.crt
    volumes:
      - ./certs:/usr/share/elasticsearch/config/certs
    ports:
      - 9201:9200
      - 9301:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1

  es-master3:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: es-master3
    environment:
      - node.roles=master
      - cluster.name=elastic-cluster
      - node.name=es-master3
      - bootstrap.memory_lock=true
      - discovery.seed_hosts=es-master1,es-master2,es-master3
      - cluster.initial_master_nodes=es-master1,es-master2,es-master3
      - xpack.security.enabled=true
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=/usr/share/elasticsearch/config/certs/es-master3/es-master3.key
      - xpack.security.transport.ssl.certificate=/usr/share/elasticsearch/config/certs/es-master3/es-master3.crt
      - xpack.security.transport.ssl.certificate_authorities=/usr/share/elasticsearch/config/certs/ca/ca.crt
    volumes:
      - ./certs:/usr/share/elasticsearch/config/certs
    ports:
      - 9202:9200
      - 9302:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1

  # Kibana Nodes
  kibana1:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: kibana1
    environment:
      - ELASTICSEARCH_URL=https://es-master1:9200
      - SERVER_HOST=0.0.0.0
      - SERVER_SSL_ENABLED=true
      - SERVER_SSL_KEY=/usr/share/kibana/config/certs/kibana1/kibana1.key
      - SERVER_SSL_CERTIFICATE=/usr/share/kibana/config/certs/kibana1/kibana1.crt
      - SERVER_SSL_CERTIFICATE_AUTHORITIES=/usr/share/kibana/config/certs/ca/ca.crt
    volumes:
      - ./certs:/usr/share/kibana/config/certs
    ports:
      - 5601:5601

  kibana2:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: kibana2
    environment:
      - ELASTICSEARCH_URL=https://es-master1:9200
      - SERVER_HOST=0.0.0.0
      - SERVER_SSL_ENABLED=true
      - SERVER_SSL_KEY=/usr/share/kibana/config/certs/kibana2/kibana2.key
      - SERVER_SSL_CERTIFICATE=/usr/share/kibana/config/certs/kibana2/kibana2.crt
      - SERVER_SSL_CERTIFICATE_AUTHORITIES=/usr/share/kibana/config/certs/ca/ca.crt
    volumes:
      - ./certs:/usr/share/kibana/config/certs
    ports:
      - 5602:5601
