- name: Configure Elasticsearch
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: elasticsearch
    group: elasticsearch
    mode: 0644

- name: Enable and start Elasticsearch
  systemd:
    name: elasticsearch
    state: started
    enabled: true
